import { BLData } from "./ActionTable";
import { ShipperProfileBoxProps } from "@/app/shippers/page";
import { DriverBoxProps } from "@/app/drivers/page";
import { CarrierProfileBoxProps } from "@/app/carriers/page";

export const activeMockData = [
  {
    bolId: "BOL1B34A",
    consignee: "DEF Industries",
    loadDesc: "Tools",
    carrier: "LMN Carriers",
    status: "In Transit",
    lastAction: "driver signed B/L",
  },
  {
    bolId: "BOL1B35B",
    consignee: "GHI Electronics",
    loadDesc: "Home Appliances",
    carrier: "OPQ Logistics",
    status: "At Pickup",
    lastAction: "submitted B/L to Carrier",
  },
  {
    bolId: "BOL1B36C",
    consignee: "JKL Fashions",
    loadDesc: "Textiles",
    carrier: "RST Shipping",
    status: "At Pickup",
    lastAction: "driver dispatched",
  },
  {
    bolId: "BOL1B37D",
    consignee: "MNO Enterprises",
    loadDesc: "Vehicles",
    carrier: "UVW Freight",
    status: "At Pickup",
    lastAction: "driver arrived at pickup location",
  },
  {
    bolId: "BOL1B38E",
    consignee: "PQR Productions",
    loadDesc: "Film Equipment",
    carrier: "XYZ Haulers",
    status: "In Transit",
    lastAction: "uploaded load image(s)",
  },
  {
    bolId: "BOL1B39F",
    consignee: "STU Retail",
    loadDesc: "Consumer Goods",
    carrier: "ABC Couriers",
    status: "In Transit",
    lastAction: "departed pickup location",
  },
  {
    bolId: "BOL1B40G",
    consignee: "VWX Tech",
    loadDesc: "Computers",
    carrier: "DEF Transport",
    status: "At Dropoff",
    lastAction: "arrived at dropoff location",
  },
  {
    bolId: "BOL1B41H",
    consignee: "YZA Designs",
    loadDesc: "Art Supplies",
    carrier: "GHI Express",
    status: "In Transit",
    lastAction: "driver is in possession of load",
  },
  {
    bolId: "BOL1B42I",
    consignee: "BCD Foods",
    loadDesc: "Groceries",
    carrier: "JKL Trucking",
    status: "Canceled",
    lastAction: "canceled",
  },
  {
    bolId: "BOL1B43J",
    consignee: "EFG Sports",
    loadDesc: "Sports Equipment",
    carrier: "MNO Freighters",
    status: "Delivered",
    lastAction: "complete",
  },
  {
    bolId: "BOL1B44K",
    consignee: "HIJ Hardware",
    loadDesc: "Building Materials",
    carrier: "PQR Lines",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B45L",
    consignee: "KLM Solutions",
    loadDesc: "Software",
    carrier: "RST Carriers",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B46M",
    consignee: "NOP Innovations",
    loadDesc: "Research Materials",
    carrier: "STU Shippers",
    status: "Delayed",
    lastAction: "Customs clearance",
  },
  {
    bolId: "BOL1B47N",
    consignee: "OPQ Co.",
    loadDesc: "Stationary",
    carrier: "UVW Couriers",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B48O",
    consignee: "RST Apparel",
    loadDesc: "Clothing",
    carrier: "XYZ Deliveries",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B34A",
    consignee: "DEF Industries",
    loadDesc: "Tools",
    carrier: "LMN Carriers",
    status: "In Transit",
    lastAction: "driver signed B/L",
  },
  {
    bolId: "BOL1B35B",
    consignee: "GHI Electronics",
    loadDesc: "Home Appliances",
    carrier: "OPQ Logistics",
    status: "At Pickup",
    lastAction: "submitted B/L to Carrier",
  },
  {
    bolId: "BOL1B36C",
    consignee: "JKL Fashions",
    loadDesc: "Textiles",
    carrier: "RST Shipping",
    status: "At Pickup",
    lastAction: "driver dispatched",
  },
  {
    bolId: "BOL1B37D",
    consignee: "MNO Enterprises",
    loadDesc: "Vehicles",
    carrier: "UVW Freight",
    status: "At Pickup",
    lastAction: "driver arrived at pickup location",
  },
  {
    bolId: "BOL1B38E",
    consignee: "PQR Productions",
    loadDesc: "Film Equipment",
    carrier: "XYZ Haulers",
    status: "In Transit",
    lastAction: "uploaded load image(s)",
  },
  {
    bolId: "BOL1B39F",
    consignee: "STU Retail",
    loadDesc: "Consumer Goods",
    carrier: "ABC Couriers",
    status: "In Transit",
    lastAction: "departed pickup location",
  },
  {
    bolId: "BOL1B40G",
    consignee: "VWX Tech",
    loadDesc: "Computers",
    carrier: "DEF Transport",
    status: "At Dropoff",
    lastAction: "arrived at dropoff location",
  },
  {
    bolId: "BOL1B41H",
    consignee: "YZA Designs",
    loadDesc: "Art Supplies",
    carrier: "GHI Express",
    status: "In Transit",
    lastAction: "driver is in possession of load",
  },
  {
    bolId: "BOL1B42I",
    consignee: "BCD Foods",
    loadDesc: "Groceries",
    carrier: "JKL Trucking",
    status: "Canceled",
    lastAction: "canceled",
  },
  {
    bolId: "BOL1B43J",
    consignee: "EFG Sports",
    loadDesc: "Sports Equipment",
    carrier: "MNO Freighters",
    status: "Delivered",
    lastAction: "complete",
  },
  {
    bolId: "BOL1B44K",
    consignee: "HIJ Hardware",
    loadDesc: "Building Materials",
    carrier: "PQR Lines",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B45L",
    consignee: "KLM Solutions",
    loadDesc: "Software",
    carrier: "RST Carriers",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B46M",
    consignee: "NOP Innovations",
    loadDesc: "Research Materials",
    carrier: "STU Shippers",
    status: "Delayed",
    lastAction: "Customs clearance",
  },
  {
    bolId: "BOL1B47N",
    consignee: "OPQ Co.",
    loadDesc: "Stationary",
    carrier: "UVW Couriers",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B48O",
    consignee: "RST Apparel",
    loadDesc: "Clothing",
    carrier: "XYZ Deliveries",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B34A",
    consignee: "DEF Industries",
    loadDesc: "Tools",
    carrier: "LMN Carriers",
    status: "In Transit",
    lastAction: "driver signed B/L",
  },
  {
    bolId: "BOL1B35B",
    consignee: "GHI Electronics",
    loadDesc: "Home Appliances",
    carrier: "OPQ Logistics",
    status: "At Pickup",
    lastAction: "submitted B/L to Carrier",
  },
  {
    bolId: "BOL1B36C",
    consignee: "JKL Fashions",
    loadDesc: "Textiles",
    carrier: "RST Shipping",
    status: "At Pickup",
    lastAction: "driver dispatched",
  },
  {
    bolId: "BOL1B37D",
    consignee: "MNO Enterprises",
    loadDesc: "Vehicles",
    carrier: "UVW Freight",
    status: "At Pickup",
    lastAction: "driver arrived at pickup location",
  },
  {
    bolId: "BOL1B38E",
    consignee: "PQR Productions",
    loadDesc: "Film Equipment",
    carrier: "XYZ Haulers",
    status: "In Transit",
    lastAction: "uploaded load image(s)",
  },
  {
    bolId: "BOL1B39F",
    consignee: "STU Retail",
    loadDesc: "Consumer Goods",
    carrier: "ABC Couriers",
    status: "In Transit",
    lastAction: "departed pickup location",
  },
  {
    bolId: "BOL1B40G",
    consignee: "VWX Tech",
    loadDesc: "Computers",
    carrier: "DEF Transport",
    status: "At Dropoff",
    lastAction: "arrived at dropoff location",
  },
  {
    bolId: "BOL1B41H",
    consignee: "YZA Designs",
    loadDesc: "Art Supplies",
    carrier: "GHI Express",
    status: "In Transit",
    lastAction: "driver is in possession of load",
  },
  {
    bolId: "BOL1B42I",
    consignee: "BCD Foods",
    loadDesc: "Groceries",
    carrier: "JKL Trucking",
    status: "Canceled",
    lastAction: "canceled",
  },
  {
    bolId: "BOL1B43J",
    consignee: "EFG Sports",
    loadDesc: "Sports Equipment",
    carrier: "MNO Freighters",
    status: "Delivered",
    lastAction: "complete",
  },
  {
    bolId: "BOL1B44K",
    consignee: "HIJ Hardware",
    loadDesc: "Building Materials",
    carrier: "PQR Lines",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B45L",
    consignee: "KLM Solutions",
    loadDesc: "Software",
    carrier: "RST Carriers",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B46M",
    consignee: "NOP Innovations",
    loadDesc: "Research Materials",
    carrier: "STU Shippers",
    status: "Delayed",
    lastAction: "Customs clearance",
  },
  {
    bolId: "BOL1B47N",
    consignee: "OPQ Co.",
    loadDesc: "Stationary",
    carrier: "UVW Couriers",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B48O",
    consignee: "RST Apparel",
    loadDesc: "Clothing",
    carrier: "XYZ Deliveries",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B34A",
    consignee: "DEF Industries",
    loadDesc: "Tools",
    carrier: "LMN Carriers",
    status: "In Transit",
    lastAction: "driver signed B/L",
  },
  {
    bolId: "BOL1B35B",
    consignee: "GHI Electronics",
    loadDesc: "Home Appliances",
    carrier: "OPQ Logistics",
    status: "At Pickup",
    lastAction: "submitted B/L to Carrier",
  },
  {
    bolId: "BOL1B36C",
    consignee: "JKL Fashions",
    loadDesc: "Textiles",
    carrier: "RST Shipping",
    status: "At Pickup",
    lastAction: "driver dispatched",
  },
  {
    bolId: "BOL1B37D",
    consignee: "MNO Enterprises",
    loadDesc: "Vehicles",
    carrier: "UVW Freight",
    status: "At Pickup",
    lastAction: "driver arrived at pickup location",
  },
  {
    bolId: "BOL1B38E",
    consignee: "PQR Productions",
    loadDesc: "Film Equipment",
    carrier: "XYZ Haulers",
    status: "In Transit",
    lastAction: "uploaded load image(s)",
  },
  {
    bolId: "BOL1B39F",
    consignee: "STU Retail",
    loadDesc: "Consumer Goods",
    carrier: "ABC Couriers",
    status: "In Transit",
    lastAction: "departed pickup location",
  },
  {
    bolId: "BOL1B40G",
    consignee: "VWX Tech",
    loadDesc: "Computers",
    carrier: "DEF Transport",
    status: "At Dropoff",
    lastAction: "arrived at dropoff location",
  },
  {
    bolId: "BOL1B41H",
    consignee: "YZA Designs",
    loadDesc: "Art Supplies",
    carrier: "GHI Express",
    status: "In Transit",
    lastAction: "driver is in possession of load",
  },
  {
    bolId: "BOL1B42I",
    consignee: "BCD Foods",
    loadDesc: "Groceries",
    carrier: "JKL Trucking",
    status: "Canceled",
    lastAction: "canceled",
  },
  {
    bolId: "BOL1B43J",
    consignee: "EFG Sports",
    loadDesc: "Sports Equipment",
    carrier: "MNO Freighters",
    status: "Delivered",
    lastAction: "complete",
  },
  {
    bolId: "BOL1B44K",
    consignee: "HIJ Hardware",
    loadDesc: "Building Materials",
    carrier: "PQR Lines",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B45L",
    consignee: "KLM Solutions",
    loadDesc: "Software",
    carrier: "RST Carriers",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B46M",
    consignee: "NOP Innovations",
    loadDesc: "Research Materials",
    carrier: "STU Shippers",
    status: "Delayed",
    lastAction: "Customs clearance",
  },
  {
    bolId: "BOL1B47N",
    consignee: "OPQ Co.",
    loadDesc: "Stationary",
    carrier: "UVW Couriers",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B48O",
    consignee: "RST Apparel",
    loadDesc: "Clothing",
    carrier: "XYZ Deliveries",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B34A",
    consignee: "DEF Industries",
    loadDesc: "Tools",
    carrier: "LMN Carriers",
    status: "In Transit",
    lastAction: "driver signed B/L",
  },
  {
    bolId: "BOL1B35B",
    consignee: "GHI Electronics",
    loadDesc: "Home Appliances",
    carrier: "OPQ Logistics",
    status: "At Pickup",
    lastAction: "submitted B/L to Carrier",
  },
  {
    bolId: "BOL1B36C",
    consignee: "JKL Fashions",
    loadDesc: "Textiles",
    carrier: "RST Shipping",
    status: "At Pickup",
    lastAction: "driver dispatched",
  },
  {
    bolId: "BOL1B37D",
    consignee: "MNO Enterprises",
    loadDesc: "Vehicles",
    carrier: "UVW Freight",
    status: "At Pickup",
    lastAction: "driver arrived at pickup location",
  },
  {
    bolId: "BOL1B38E",
    consignee: "PQR Productions",
    loadDesc: "Film Equipment",
    carrier: "XYZ Haulers",
    status: "In Transit",
    lastAction: "uploaded load image(s)",
  },
  {
    bolId: "BOL1B39F",
    consignee: "STU Retail",
    loadDesc: "Consumer Goods",
    carrier: "ABC Couriers",
    status: "In Transit",
    lastAction: "departed pickup location",
  },
  {
    bolId: "BOL1B40G",
    consignee: "VWX Tech",
    loadDesc: "Computers",
    carrier: "DEF Transport",
    status: "At Dropoff",
    lastAction: "arrived at dropoff location",
  },
  {
    bolId: "BOL1B41H",
    consignee: "YZA Designs",
    loadDesc: "Art Supplies",
    carrier: "GHI Express",
    status: "In Transit",
    lastAction: "driver is in possession of load",
  },
  {
    bolId: "BOL1B42I",
    consignee: "BCD Foods",
    loadDesc: "Groceries",
    carrier: "JKL Trucking",
    status: "Canceled",
    lastAction: "canceled",
  },
  {
    bolId: "BOL1B43J",
    consignee: "EFG Sports",
    loadDesc: "Sports Equipment",
    carrier: "MNO Freighters",
    status: "Delivered",
    lastAction: "complete",
  },
  {
    bolId: "BOL1B44K",
    consignee: "HIJ Hardware",
    loadDesc: "Building Materials",
    carrier: "PQR Lines",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B45L",
    consignee: "KLM Solutions",
    loadDesc: "Software",
    carrier: "RST Carriers",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
  {
    bolId: "BOL1B46M",
    consignee: "NOP Innovations",
    loadDesc: "Research Materials",
    carrier: "STU Shippers",
    status: "Delayed",
    lastAction: "Customs clearance",
  },
  {
    bolId: "BOL1B47N",
    consignee: "OPQ Co.",
    loadDesc: "Stationary",
    carrier: "UVW Couriers",
    status: "In Transit",
    lastAction: "Shipment picked up",
  },
  {
    bolId: "BOL1B48O",
    consignee: "RST Apparel",
    loadDesc: "Clothing",
    carrier: "XYZ Deliveries",
    status: "Delivered",
    lastAction: "Delivered to consignee",
  },
];

export const completeMockData = [
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
  {
    bolId: "BOL2B36C",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B34A",
    consignee: "Consignee 1",
    loadDesc: "Load Description 1",
    carrier: "Carrier 1",
    paymentType: "prepaid",
  },
  {
    bolId: "BOL2B35B",
    consignee: "Consignee 2",
    loadDesc: "Load Description 2",
    carrier: "Carrier 2",
    paymentType: "collect",
  },
];

export const mockActionData = {
  bolId: 12345768,
  shipper: {
    name: "Ship Co.",
    address: "34567 Bryant St Panorama, CA 91402",
    phone: "(777) 888-8888",
    email: "support@northropgrumman.com",
  },
  carrier: {
    name: "Carry Inc.",
    address: "888 DriveRoad Los Angeles, CA 90210",
    phone: "(123) 888-8888",
    email: "support@aero.com",
  },
  consignee: {
    name: "Rec. Co.",
    address: "12345 Road Los Angeles, CA 90210",
    phone: "(888) 888-8888",
    email: "contact@recco.com",
  },
  load: {
    packageType: "Boxes",
    quantity: 7,
    description: "FLAMMABLE LIQUID,(2-Chemical ...)",
    volume: "40L",
    weight: "400lbs",
    classType: "Hazardous",
  },
  actionData: [
    {
      date: "2023-08-19",
      time: "09:00:00",
      agent: "Shipper",
      action: "signed B/L",
    },
    {
      date: "2023-08-19",
      time: "09:01:00",
      agent: "Shipper",
      action: "submitted B/L to Carrier",
    },
    // {
    //   date: "2023-08-19",
    //   time: "09:01:00",
    //   agent: "Carrier",
    //   action: "dispatched",
    // },
    // {
    //   date: "2023-08-19",
    //   time: "10:00:00",
    //   agent: "Driver",
    //   action: "arrived at pickup location",
    // },
    // {
    //   date: "2023-08-19",
    //   time: "10:20:00",
    //   agent: "Driver",
    //   action: "uploaded load image(s)",
    // },
    // {
    //   date: "2023-08-19",
    //   time: "10:27:00",
    //   agent: "Driver",
    //   action: "departed pickup location",
    // },
    // {
    //   date: "2023-08-19",
    //   time: "13:24:00",
    //   agent: "Driver",
    //   action: "arrived at dropoff location",
    // },
    // {
    //   date: "2023-08-19",
    //   time: "13:47:00",
    //   agent: "Consignee",
    //   action: "is in possession of load",
    // },
    // {
    //   date: "2023-08-19",
    //   time: "13:48:00",
    //   agent: "Consignee",
    //   action: "complete",
    // },
  ],
};

export const carrierActiveMockData = [
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Smite",
    status: "driver signed B/L",
    paymentType: "Collect",
    placedAt: "2023-08-20 17:33:00",
  },
  {
    shipper: "Store Co.",
    consignee: "XYZ Inc.",
    driver: "-",
    status: "submitted B/L to Carrier",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 4:23:00",
  },
  {
    shipper: "XYZ Inc",
    consignee: "Store Co.",
    driver: "Tom Willac",
    status: "dispatched",
    paymentType: "Collect",
    placedAt: "2023-08-21 11:30:00",
  },
  {
    shipper: "Space Co",
    consignee: "Airline",
    driver: "Bob Dotten",
    status: "arrived at pickup location",
    paymentType: "Collect",
    placedAt: "2023-08-27 1:32:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Greg",
    status: "uploaded load image(s)",
    paymentType: "Collect",
    placedAt: "2023-08-20 08:37:00",
  },
  {
    shipper: "Chemical Co.",
    consignee: "XYZ Inc.",
    driver: "Adam Reverant",
    status: "departed pickup location",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 06:00:00",
  },
  {
    shipper: "Airline Co.",
    consignee: "Bolts Inc.",
    driver: "Tee Tom",
    status: "arrived at dropoff location",
    paymentType: "Collect",
    placedAt: "2023-08-20 21:30:00",
  },
  {
    shipper: "Store Inc.",
    consignee: "China Co.",
    driver: "Bob Graham",
    status: "is in possession of load",
    paymentType: "Collect",
    placedAt: "2023-08-23 14:00:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "signed B/L",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Space Co.",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "submitted B/L to Carrier",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Inc.",
    consignee: "ZXY INc",
    driver: "Tee Tom",
    status: "dispatched",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Inc",
    consignee: "Airline Co.",
    driver: "Bob Doe",
    status: "arrived at pickup location",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "uploaded load image(s)",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Boeing",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "In Transit",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "PPG",
    consignee: "Anaplex",
    driver: "Tee Tom",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "SpaceX",
    consignee: "ChinaAir",
    driver: "Bob Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Boeing",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "In Transit",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "PPG",
    consignee: "Anaplex",
    driver: "Tee Tom",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "SpaceX",
    consignee: "ChinaAir",
    driver: "Bob Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Smite",
    status: "driver signed B/L",
    paymentType: "Collect",
    placedAt: "2023-08-20 17:33:00",
  },
  {
    shipper: "Store Co.",
    consignee: "XYZ Inc.",
    driver: "-",
    status: "submitted B/L to Carrier",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 4:23:00",
  },
  {
    shipper: "XYZ Inc",
    consignee: "Store Co.",
    driver: "Tom Willac",
    status: "dispatched",
    paymentType: "Collect",
    placedAt: "2023-08-21 11:30:00",
  },
  {
    shipper: "Space Co",
    consignee: "Airline",
    driver: "Bob Dotten",
    status: "arrived at pickup location",
    paymentType: "Collect",
    placedAt: "2023-08-27 1:32:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Greg",
    status: "uploaded load image(s)",
    paymentType: "Collect",
    placedAt: "2023-08-20 08:37:00",
  },
  {
    shipper: "Chemical Co.",
    consignee: "XYZ Inc.",
    driver: "Adam Reverant",
    status: "departed pickup location",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 06:00:00",
  },
  {
    shipper: "Airline Co.",
    consignee: "Bolts Inc.",
    driver: "Tee Tom",
    status: "arrived at dropoff location",
    paymentType: "Collect",
    placedAt: "2023-08-20 21:30:00",
  },
  {
    shipper: "Store Inc.",
    consignee: "China Co.",
    driver: "Bob Graham",
    status: "is in possession of load",
    paymentType: "Collect",
    placedAt: "2023-08-23 14:00:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "signed B/L",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Space Co.",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "submitted B/L to Carrier",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Inc.",
    consignee: "ZXY INc",
    driver: "Tee Tom",
    status: "dispatched",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Inc",
    consignee: "Airline Co.",
    driver: "Bob Doe",
    status: "arrived at pickup location",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "uploaded load image(s)",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Boeing",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "In Transit",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "PPG",
    consignee: "Anaplex",
    driver: "Tee Tom",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "SpaceX",
    consignee: "ChinaAir",
    driver: "Bob Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Boeing",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "In Transit",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "PPG",
    consignee: "Anaplex",
    driver: "Tee Tom",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "SpaceX",
    consignee: "ChinaAir",
    driver: "Bob Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Smite",
    status: "driver signed B/L",
    paymentType: "Collect",
    placedAt: "2023-08-20 17:33:00",
  },
  {
    shipper: "Store Co.",
    consignee: "XYZ Inc.",
    driver: "-",
    status: "submitted B/L to Carrier",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 4:23:00",
  },
  {
    shipper: "XYZ Inc",
    consignee: "Store Co.",
    driver: "Tom Willac",
    status: "dispatched",
    paymentType: "Collect",
    placedAt: "2023-08-21 11:30:00",
  },
  {
    shipper: "Space Co",
    consignee: "Airline",
    driver: "Bob Dotten",
    status: "arrived at pickup location",
    paymentType: "Collect",
    placedAt: "2023-08-27 1:32:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Greg",
    status: "uploaded load image(s)",
    paymentType: "Collect",
    placedAt: "2023-08-20 08:37:00",
  },
  {
    shipper: "Chemical Co.",
    consignee: "XYZ Inc.",
    driver: "Adam Reverant",
    status: "departed pickup location",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 06:00:00",
  },
  {
    shipper: "Airline Co.",
    consignee: "Bolts Inc.",
    driver: "Tee Tom",
    status: "arrived at dropoff location",
    paymentType: "Collect",
    placedAt: "2023-08-20 21:30:00",
  },
  {
    shipper: "Store Inc.",
    consignee: "China Co.",
    driver: "Bob Graham",
    status: "is in possession of load",
    paymentType: "Collect",
    placedAt: "2023-08-23 14:00:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "signed B/L",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Space Co.",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "submitted B/L to Carrier",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Inc.",
    consignee: "ZXY INc",
    driver: "Tee Tom",
    status: "dispatched",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Inc",
    consignee: "Airline Co.",
    driver: "Bob Doe",
    status: "arrived at pickup location",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "uploaded load image(s)",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Boeing",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "In Transit",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "PPG",
    consignee: "Anaplex",
    driver: "Tee Tom",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "SpaceX",
    consignee: "ChinaAir",
    driver: "Bob Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "ABC Corp.",
    consignee: "XYZ Inc.",
    driver: "John Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "Boeing",
    consignee: "XYZ Inc.",
    driver: "Feee Regge",
    status: "In Transit",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "PPG",
    consignee: "Anaplex",
    driver: "Tee Tom",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  {
    shipper: "SpaceX",
    consignee: "ChinaAir",
    driver: "Bob Doe",
    status: "In Transit",
    paymentType: "Collect",
    placedAt: "2023-08-20 14:30:00",
  },
  // ... other entries ...
];

export const carrierCompleteMockData = [
  {
    shipper: "DEF Corp.",
    consignee: "LMN Inc.",
    driver: "Jane Smith",
    completedAt: "2023-08-18 16:45:00",
    paymentType: "Prepaid",

    placedAt: "2023-08-15 09:10:00",
  },
  {
    shipper: "XYZ Enterprises",
    consignee: "OPQ Ltd.",
    driver: "John Doe",
    completedAt: "2023-08-20 14:25:00",
    paymentType: "Collect",
    placedAt: "2023-08-17 10:15:00",
  },
  {
    shipper: "ABC Industries",
    consignee: "HIJ Co.",
    driver: "Emily Davis",
    completedAt: "2023-08-22 15:30:00",
    paymentType: "Prepaid",
    placedAt: "2023-08-19 08:40:00",
  },
  {
    shipper: "RST Corp.",
    consignee: "UVW Group",
    driver: "Robert Brown",
    completedAt: "2023-08-19 12:05:00",
    paymentType: "Collect",
    placedAt: "2023-08-16 11:00:00",
  },
  {
    shipper: "GHI Services",
    consignee: "KLM Solutions",
    driver: "Alice Johnson",
    completedAt: "2023-08-23 13:45:00",
    paymentType: "Prepaid",
    placedAt: "2023-08-20 09:50:00",
  },
  {
    shipper: "STU Manufacturing",
    consignee: "XYZ Innovations",
    driver: "William White",
    completedAt: "2023-08-17 17:10:00",
    paymentType: "Collect",
    placedAt: "2023-08-14 10:25:00",
  },
  {
    shipper: "PQR Tech",
    consignee: "ABC Design",
    driver: "Olivia Green",
    completedAt: "2023-08-24 16:00:00",
    paymentType: "Prepaid",
    placedAt: "2023-08-21 08:30:00",
  },
  {
    shipper: "MNO Industries",
    consignee: "DEF Productions",
    driver: "James Black",
    completedAt: "2023-08-21 14:15:00",
    paymentType: "Collect",
    placedAt: "2023-08-18 09:20:00",
  },
  {
    shipper: "VWX Solutions",
    consignee: "STU Tech",
    driver: "Ella Gray",
    completedAt: "2023-08-25 13:30:00",
    paymentType: "Prepaid",
    placedAt: "2023-08-22 10:10:00",
  },
  {
    shipper: "IJK Enterprise",
    consignee: "PQR Ventures",
    driver: "Michael Blue",
    completedAt: "2023-08-26 12:40:00",
    paymentType: "Collect",
    placedAt: "2023-08-23 08:55:00",
  },
  {
    shipper: "YZA Corp.",
    consignee: "GHI Labs",
    driver: "Sophia Turner",
    completedAt: "2023-08-27 15:00:00",
    paymentType: "Prepaid",
    placedAt: "2023-08-24 10:05:00",
  },
  {
    shipper: "BCD Innovations",
    consignee: "IJK Creative",
    driver: "Benjamin King",
    completedAt: "2023-08-28 16:35:00",
    paymentType: "Collect",
    placedAt: "2023-08-25 09:45:00",
  },
  {
    shipper: "EFG Tech",
    consignee: "YZA Digital",
    driver: "Charlotte Woods",
    completedAt: "2023-08-29 17:20:00",
    paymentType: "Prepaid",
    placedAt: "2023-08-26 08:50:00",
  },
  {
    shipper: "KLM Logistics",
    consignee: "BCD Solutions",
    driver: "Daniel Wright",
    completedAt: "2023-08-30 14:50:00",
    paymentType: "Collect",
    placedAt: "2023-08-27 09:15:00",
  },
  {
    shipper: "NOP Services",
    consignee: "EFG Studios",
    driver: "Amelia Clark",
    completedAt: "2023-08-31 15:55:00",
    paymentType: "Prepaid",
    placedAt: "2023-08-28 08:35:00",
  },
  {
    shipper: "QRS Manufacturing",
    consignee: "KLM Analytics",
    driver: "Ethan Hall",
    completedAt: "2023-09-01 16:45:00",
    paymentType: "Collect",
    placedAt: "2023-08-29 10:20:00",
  },
];

export const carrierShipperActiveMockData = [
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    driver: "Alice Johnson",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    driver: "Sam Johnson",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  // ... other entries ...
];

export const carrierShipperCompleteMockData = [
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    driver: "Alice Thompson",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    driver: "Charlie Brown",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    driver: "Eva Green",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    driver: "Alice Thompson",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    driver: "Charlie Brown",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    driver: "Eva Green",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    driver: "Alice Thompson",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    driver: "Charlie Brown",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    driver: "Eva Green",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    driver: "Bob Williams",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    driver: "Alice Thompson",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    driver: "Charlie Brown",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    driver: "Eva Green",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
];

export const shipperCarrierActiveMockData = [
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    driver: "Ron Artest",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "Boeing",
    placedAt: "2023-08-19 12:00:00",
    driver: "Dave Johnson",
    status: "With Driver",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PPG",
    placedAt: "2023-08-19 12:00:00",
    status: "in route to receiver",
    paymentType: "prepaid",
    lastAction: "Checked-In",
  },
  {
    consignee: "SpaceX",
    placedAt: "2023-08-19 12:00:00",
    status: "At Pickup Location",
    paymentType: "Collect",
    lastAction: "Checked-In",
  },
  {
    consignee: "PQR Inc.",
    placedAt: "2023-08-19 12:00:00",
    status: "Delayed",
    paymentType: "Prepaid",
    lastAction: "Checked-In",
  },
];

export const shipperCarrierCompleteMockData = [
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "STU Corp.",
    placedAt: "2023-08-16 10:20:00",
    completedAt: "2023-08-17 11:50:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "VWX Industries",
    placedAt: "2023-08-14 09:25:00",
    completedAt: "2023-08-15 12:40:00",
    paymentType: "Collect",
  },
  {
    consignee: "ABC Traders",
    placedAt: "2023-08-13 15:15:00",
    completedAt: "2023-08-14 16:05:00",
    paymentType: "Prepaid",
  },
  {
    consignee: "ZYZ Enterprises",
    placedAt: "2023-07-01 10:10:00",
    completedAt: "2023-07-02 11:20:00",
    paymentType: "Collect",
  },
];

export const mockShipperData = [
  {
    name: "Space Co.",
    activeBls: 5,
    completeBls: 10,
    driversAllocated: 3,
    shipperId: "s1",
  },
  {
    name: "Chemic Inc",
    activeBls: 7,
    completeBls: 8,
    driversAllocated: 4,
    shipperId: "s2",
  },
  {
    name: "Inc Co.",
    activeBls: 10,
    completeBls: 20,
    driversAllocated: 5,
    shipperId: "s3",
  },
  {
    name: "Ship Inc,",
    activeBls: 2,
    completeBls: 15,
    driversAllocated: 2,
    shipperId: "s4",
  },
  {
    name: "China Co.",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Air Co.",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Store Shop.",
    activeBls: 1,
    completeBls: 12,
    driversAllocated: 7,
    shipperId: "s5",
  },
  {
    name: "WalStore",
    activeBls: 6,
    completeBls: 1,
    driversAllocated: 1,
    shipperId: "s5",
  },
  {
    name: "Harbor CO.",
    activeBls: 16,
    completeBls: 112,
    driversAllocated: 11,
    shipperId: "s5",
  },
  {
    name: "Small Biz. Co ",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "XYZ Inc.",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "ABC Co.",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Co Company",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "ShipperCo.",
    activeBls: 5,
    completeBls: 10,
    driversAllocated: 3,
    shipperId: "s1",
  },
  {
    name: "X Co.",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "PPG",
    activeBls: 7,
    completeBls: 8,
    driversAllocated: 4,
    shipperId: "s2",
  },
  {
    name: "Northrop Grumman",
    activeBls: 10,
    completeBls: 20,
    driversAllocated: 5,
    shipperId: "s3",
  },
  {
    name: "Anaplex",
    activeBls: 2,
    completeBls: 15,
    driversAllocated: 2,
    shipperId: "s4",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Nasa",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "SpaceX",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Nasa",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "SpaceX",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Nasa",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },

  {
    name: "SpaceX",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
  {
    name: "Airlink",
    activeBls: 6,
    completeBls: 12,
    driversAllocated: 3,
    shipperId: "s5",
  },
];

export const mockCarrierData = [
  {
    name: "Freight Man Co.",
    activeBls: 5,
    completeBls: 10,
    carrierId: "s1",
  },
];

export const mockDriverData = [
  {
    driverId: "001",
    activeBls: 5,
    completeBls: 20,
    status: "in Route to pickup",
    name: "John Doe",
  },
  {
    driverId: "002",
    activeBls: 3,
    completeBls: 15,
    status: "in Route to pickup",
    name: "Jane Smith",
  },
  {
    driverId: "003",
    activeBls: 7,
    completeBls: 30,
    status: "in Route to Dropoff",
    name: "Alice Johnson",
  },
  {
    driverId: "004",
    activeBls: 2,
    completeBls: 10,
    status: "in Route to pickup",
    name: "Bob Wilson",
  },
  {
    driverId: "005",
    activeBls: 1,
    completeBls: 8,
    status: "in Route to pickup",
    name: "Charlie Brown",
  },
  {
    driverId: "006",
    activeBls: 4,
    completeBls: 14,
    status: "in Route to Dropoff",
    name: "Eve Adams",
  },
  {
    driverId: "007",
    activeBls: 6,
    completeBls: 16,
    status: "Suspended",
    name: "Franklin Turner",
  },
  {
    driverId: "008",
    activeBls: 2,
    completeBls: 18,
    status: "Inactive",
    name: "Grace Lee",
  },
  {
    driverId: "009",
    activeBls: 3,
    completeBls: 19,
    status: "in Route to Dropoff",
    name: "Henry Miller",
  },
  {
    driverId: "010",
    activeBls: 5,
    completeBls: 15,
    status: "in Route to Dropoff",
    name: "Irene Carter",
  },
  {
    driverId: "011",
    activeBls: 1,
    completeBls: 9,
    status: "Inactive",
    name: "Jack Gray",
  },
  {
    driverId: "012",
    activeBls: 4,
    completeBls: 12,
    status: "at Dropoff",
    name: "Kathy Simmons",
  },
  {
    driverId: "013",
    activeBls: 6,
    completeBls: 22,
    status: "at Pickup",
    name: "Liam Rogers",
  },
  {
    driverId: "014",
    activeBls: 3,
    completeBls: 11,
    status: "in Route to Dropoff",
    name: "Monica Clark",
  },
  {
    driverId: "015",
    activeBls: 2,
    completeBls: 17,
    status: "in Route to Dropoff",
    name: "Nathan Webb",
  },
  {
    driverId: "016",
    activeBls: 5,
    completeBls: 20,
    status: "in Route to Dropoff",
    name: "Olivia Sanders",
  },
  {
    driverId: "017",
    activeBls: 1,
    completeBls: 13,
    status: "in Route to Dropoff",
    name: "Peter Bennett",
  },
  {
    driverId: "018",
    activeBls: 4,
    completeBls: 24,
    status: "in Route to pickup",
    name: "Quinn King",
  },
  {
    driverId: "019",
    activeBls: 6,
    completeBls: 27,
    status: "in Route to pickup",
    name: "Rebecca Lopez",
  },
  {
    driverId: "020",
    activeBls: 3,
    completeBls: 15,
    status: "in Route to pickup",
    name: "Steve Howard",
  },
];

export const mockDailyLogData = [
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
  {
    shipper: "ABC Company",
    consignee: "XYZ Retail",
    activity: "signed B/L",
    dateTime: "2023-08-21 09:00:00",
  },
  {
    shipper: "Widgets Inc.",
    consignee: "123 Stores",
    activity: "arrived at pickup location",
    dateTime: "2023-08-21 11:15:00",
  },
  {
    shipper: "Tech Corp",
    consignee: "Electro World",
    activity: "uploaded load image(s)",
    dateTime: "2023-08-21 14:30:00",
  },
  {
    shipper: "Fresh Produce Ltd.",
    consignee: "Marketplace",
    activity: "departed pickup location",
    dateTime: "2023-08-21 16:45:00",
  },
  {
    shipper: "Auto Parts Makers",
    consignee: "Car Repair Central",
    activity: "arrived at dropoff location",
    dateTime: "2023-08-21 18:30:00",
  },
  {
    shipper: "Manufacturers Inc.",
    consignee: "Trade Hub",
    activity: "is in possession of load",
    dateTime: "2023-08-21 20:00:00",
  },
  {
    shipper: "Distributors Corp.",
    consignee: "Retail Outlet",
    activity: "complete",
    dateTime: "2023-08-21 21:45:00",
  },
];
